language: java

jdk:
  - oraclejdk8
  
branches:
  only:
    - master
    - develop
    
notifications:
  slack: tpv-miw:RR3NECTV3PaLvPZOUUd8qF7O
  email:
    recipients:
      - j.bernal@upm.es
      
services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tpv;'
      
script: mvn verify --settings settings.xml
