language: java

jdk:
  - oraclejdk8
  
branches:
  only:
    - master
    - develop
    
notifications:
  email:
    recipients:
      - j.bernal@upm.es
      
services:
  - mysql
      
script: mvn verify --settings settings.xml
