language: java

jdk:
  - oraclejdk8
  
branches:
  only:
    - master
    - develop
    
notifications:
  slack: tpv-miw:RR3NECTV3PaLvPZOUUd8qF7O
  email:
    recipients:
      - j.bernal@upm.es
      
services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tpv;'
      
script: mvn verify --settings settings.xml

deploy:
  provider: heroku
  api_key:
    secure: jjvDjvl23nG0FouLmCi+wzXSbMHbz7Lq8modAjw5vfzMQPjjMC4siBZv1Z8OJe+y0EuA3T+S/wS0yoW2JyPStvAb1UcSOucusMa8sZhfT+3G4CmoondgOA4CTZvbe6uTofFI8J57qSTe0JPxBM4NeXoIHL5qU9HZE7G0GF4mF3kHM06/JOCL0OlBoie0FN47n4ifsdapnM9AB0wOyVmzY7bPRxcDCD6xXGXB8f83opdRP/560RjfXqkOXl3z/GnRgRt4fwzA3elGEsMg8JWHV1ucC7j9aM9yiuVEknXdQjSuLoNEG7W0IU3B7prF7S4IAZCGmSp5HuxTs7NFP3F/ZHCNIc9PQYDTsEW5AsZWEyimstrb9beWAGUVHxn6sz8NZ54rft6tQ0UouT3/vErh/iYPNknsBxtvo3jdjdxirs7FjNL/ocQ8/gI/Ii57W/bOpxH8dtSVHx7Xhqz4sxOzcH6hFS5qBzLeT3xpPypfWnC7AzxdnzmDyqEE3G3Szm2MAxCk917ueJIKud1cVpLj4UqywH0iB4kfP1Xg8/RhPuytjeubi3ZabO4qasfuZqWw+9N1WPmZjhY+Ama3ISlBUF8NlIbC3iZXEf6GL1vdvbuLmb9muW54kP6D+dlfw8+9K4uGG2MFwnWeMHSBi7GzN64kaKbkrfLp8L+Ji4yKie8=
  app: tpv-miw  